import React from 'react';
import {
    Home,
    Building2,
    Video,
    Settings,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    X,
    Menu,
    Info,
    Camera,
    Layers,
    LayoutGrid,
    Map,
    Plus,
    Trash2,
    Edit,
    Search,
    Filter,
    Check,
    AlertCircle,
    Eye,
    Share2,
    Download,
    Mail,
    User,
    Users,
    LogOut,
    Moon,
    Sun,
    Maximize,
    Minimize,
    QrCode,
    FileText,
    Clock,
    Briefcase,
    Star,
    ShieldCheck,
    CreditCard,
    Database,
    Link,
    Copy,
    PlusCircle,
    UserPlus,
    ArrowRightLeft,
    Undo,
    Redo,
    Circle,
    Square,
    Bed,
    Tag,
    Upload,
    ArrowLeft,
    Sparkles,
    Building,
    Key,
    Folder,
    Expand,
    MoreVertical,
    Clipboard,
    ZoomIn,
    ZoomOut,
    Undo2,
    Redo2,
    Hexagon,
    ChevronsLeft,
    ChevronsRight,
    Heart
} from 'lucide-react';

/**
 * Icons bridge component.
 * This should be the primary way to import icons in the project.
 * Note: Use strokeWidth={1.5} to maintain the "Nordic Cinematic" aesthetic.
 */

export const Icons = {
    // Navigation & Core
    Home: (props: any) => <Home strokeWidth={1.5} {...props} />,
    Project: (props: any) => <Building2 strokeWidth={1.5} {...props} />,
    Viewer: (props: any) => <Video strokeWidth={1.5} {...props} />,
    Settings: (props: any) => <Settings strokeWidth={1.5} {...props} />,
    Dashboard: (props: any) => <LayoutGrid strokeWidth={1.5} {...props} />,

    // UI Utilities
    Close: (props: any) => <X strokeWidth={1.5} {...props} />,
    Menu: (props: any) => <Menu strokeWidth={1.5} {...props} />,
    ChevronRight: (props: any) => <ChevronRight strokeWidth={1.5} {...props} />,
    ChevronLeft: (props: any) => <ChevronLeft strokeWidth={1.5} {...props} />,
    ChevronDown: (props: any) => <ChevronDown strokeWidth={1.5} {...props} />,
    ChevronUp: (props: any) => <ChevronUp strokeWidth={1.5} {...props} />,
    Plus: (props: any) => <Plus strokeWidth={1.5} {...props} />,
    Trash: (props: any) => <Trash2 strokeWidth={1.5} {...props} />,
    Edit: (props: any) => <Edit strokeWidth={1.5} {...props} />,
    Search: (props: any) => <Search strokeWidth={1.5} {...props} />,
    Filter: (props: any) => <Filter strokeWidth={1.5} {...props} />,
    Check: (props: any) => <Check strokeWidth={1.5} {...props} />,
    Info: (props: any) => <Info strokeWidth={1.5} {...props} />,
    Alert: (props: any) => <AlertCircle strokeWidth={1.5} {...props} />,
    Eye: (props: any) => <Eye strokeWidth={1.5} {...props} />,
    Share: (props: any) => <Share2 strokeWidth={1.5} {...props} />,
    Download: (props: any) => <Download strokeWidth={1.5} {...props} />,

    // Feature Specific
    Camera: (props: any) => <Camera strokeWidth={1.5} {...props} />,
    VideoCamera: (props: any) => <Video strokeWidth={1.5} {...props} />,
    Image: (props: any) => <Maximize strokeWidth={1.5} {...props} />,
    Gallery: (props: any) => <Maximize strokeWidth={1.5} {...props} />,
    Map: (props: any) => <Map strokeWidth={1.5} {...props} />,
    Layers: (props: any) => <Layers strokeWidth={1.5} {...props} />,
    GridView: (props: any) => <LayoutGrid strokeWidth={1.5} {...props} />,

    // Communication & Auth
    Mail: (props: any) => <Mail strokeWidth={1.5} {...props} />,
    User: (props: any) => <User strokeWidth={1.5} {...props} />,
    Users: (props: any) => <Users strokeWidth={1.5} {...props} />,
    UserPlus: (props: any) => <UserPlus strokeWidth={1.5} {...props} />,
    Logout: (props: any) => <LogOut strokeWidth={1.5} {...props} />,
    Profile: (props: any) => <User strokeWidth={1.5} {...props} />,

    // Appearance
    Moon: (props: any) => <Moon strokeWidth={1.5} {...props} />,
    Sun: (props: any) => <Sun strokeWidth={1.5} {...props} />,
    Magic: (props: any) => <Sparkles strokeWidth={1.5} {...props} />,

    // Technical
    QrCode: (props: any) => <QrCode strokeWidth={1.5} {...props} />,
    Document: (props: any) => <FileText strokeWidth={1.5} {...props} />,
    History: (props: any) => <Clock strokeWidth={1.5} {...props} />,
    Database: (props: any) => <Database strokeWidth={1.5} {...props} />,
    Shield: (props: any) => <ShieldCheck strokeWidth={1.5} {...props} />,
    ShieldCheck: (props: any) => <ShieldCheck strokeWidth={1.5} {...props} />,
    ShieldCircle: (props: any) => <ShieldCheck strokeWidth={1.5} {...props} />,
    CreditCard: (props: any) => <CreditCard strokeWidth={1.5} {...props} />,
    Link: (props: any) => <Link strokeWidth={1.5} {...props} />,
    Copy: (props: any) => <Copy strokeWidth={1.5} {...props} />,
    Duplicate: (props: any) => <Copy strokeWidth={1.5} {...props} />,
    Clipboard: (props: any) => <Clipboard strokeWidth={1.5} {...props} />,
    Key: (props: any) => <Key strokeWidth={1.5} {...props} />,

    // Geometric/Misc / Tools
    Circle: (props: any) => <Circle strokeWidth={1.5} {...props} />,
    Polygon: (props: any) => <Hexagon strokeWidth={1.5} {...props} />,
    Undo: (props: any) => <Undo2 strokeWidth={1.5} {...props} />,
    Redo: (props: any) => <Redo2 strokeWidth={1.5} {...props} />,
    ArrowsLeftRight: (props: any) => <ArrowRightLeft strokeWidth={1.5} {...props} />,
    ZoomIn: (props: any) => <ZoomIn strokeWidth={1.5} {...props} />,
    ZoomOut: (props: any) => <ZoomOut strokeWidth={1.5} {...props} />,
    FitToScreen: (props: any) => <Expand strokeWidth={1.5} {...props} />,
    DotsVertical: (props: any) => <MoreVertical strokeWidth={1.5} {...props} />,

    // Unit & Project Specific
    Area: (props: any) => <Maximize strokeWidth={1.5} {...props} />,
    Rooms: (props: any) => <Bed strokeWidth={1.5} {...props} />,
    Tag: (props: any) => <Tag strokeWidth={1.5} {...props} />,
    Upload: (props: any) => <Upload strokeWidth={1.5} {...props} />,
    Back: (props: any) => <ArrowLeft strokeWidth={1.5} {...props} />,
    Building: (props: any) => <Building strokeWidth={1.5} {...props} />,
    Folder: (props: any) => <Folder strokeWidth={1.5} {...props} />,
    ChevronDoubleLeft: (props: any) => <ChevronsLeft strokeWidth={1.5} {...props} />,
    ChevronDoubleRight: (props: any) => <ChevronsRight strokeWidth={1.5} {...props} />,
    Heart: (props: any) => <Heart strokeWidth={1.5} {...props} />,
};
